### PR TITLE
Ubuntu server doc rucio-server-ubuntu.md

### PR DESCRIPTION
**Pull request by cfenell**
Hi, I have updated the instructions for install on Ubuntu.
Added a note on the required Apache option 
     SSLOptions +LegacyDNStringFormat

### CODE REVIEW

**Comment by bari12** [comment]
Hi @cfenell 
I made some adaptions so the tests run through. A few minor items:

Can you add a block like

```
---
id: installing_server
title: Installing Rucio Server
---
```

on the top, similar to other doc files https://github.com/rucio/documentation/blob/main/docs/operator/installing_server.md

Also all headers need to be moved in by one `#` (so adding one to each) - this is due to the way the doc is then compiled.

Thanks!

**Comment by cfenell** [comment]
Thanks, done and pushed to my branch!

**Comment by cfenell** [comment]
That is, you should be able to merge the one that is found in
 https://github.com/cfenell/rucio-documentation/tree/ubuntu-server/docs

**Comment by cfenell** [comment]
Also added the relevant comment to the sample Apache configuration in the appendix.

**Pull request closed without merging**
