### PR TITLE
#12 Upgrading to Modern Font

### LINKED ISSUE #12: Upgrading to modern font
## Motivation
Currently the Rucio Documentation website does not explicitly specify any font family, and uses the standard fall-back fonts for displaying the text. This leads to inconsistent look across devices since the website will only use the fall-back fonts for display. While the fall-back fonts should be present in case the primary and the secondary fonts fail to load.

## Modification
Using some modern font pairing will improve the overall theme of the Rucio Documentation. 

* Preferably since the two graphical user interfaces Rucio provides use Inter font family for its typography, the same may be reflected here for consistent theming.
* The [Inter font family](https://fonts.google.com/specimen/Inter) goes well with [Rubik Font](https://fonts.google.com/specimen/Rubik) and they form a pairing. Suggested to use Inter for Headings and Rubik for overline, paragraphs, and body text.

### PR DESCRIPTION
**Pull request by palakyadav1807**
Made changes in -

- `website/siteConfig.js `-> added stylesheets (custom.css and google fonts URL)

- `website/static/css/custom.css` -> added font styles to main heading, sub-headings and body.
                     -> used Inter font family for headings and Rubik font family for rest.

This closes #12

### CODE REVIEW

**Comment by viveknigam3003** [comment]
@divya-mohan0209 please review this PR, so that I may be merged.

**Review by divya-mohan0209 — APPROVED** [review]
LGTM @bari12 : Please provide your review.

**Comment by palakyadav1807** [comment]
@bari12  Can you please provide your review too?

**Comment by bari12** [comment]
Apologies :-) I think I missed the notifications for this repo. Looks good.

**Comment by viveknigam3003** [comment]
@divya-mohan0209 please have a look at this one, GH actions is showing some error:
```bash
remote: Permission to rucio/documentation.git denied to github-actions[bot].
fatal: unable to access '***github.com/rucio/documentation.git/': The requested URL returned error: 403
```

**Comment by divya-mohan0209** [comment]
@viveknigam3003 : We're working on it, shall keep you posted.

**Comment by viveknigam3003** [comment]
> @viveknigam3003 : We're working on it, shall keep you posted.

Great! Thanks 😄

**Comment by divya-mohan0209** [comment]
> @divya-mohan0209 please have a look at this one, GH actions is showing some error:
> 
> ```shell
> remote: Permission to rucio/documentation.git denied to github-actions[bot].
> fatal: unable to access '***github.com/rucio/documentation.git/': The requested URL returned error: 403
> ```
> 
> So the changes are not pushed to GH Pages :/

Should work now.

**Comment by viveknigam3003** [comment]
> > @divya-mohan0209 please have a look at this one, GH actions is showing some error:
> > ```shell
> > remote: Permission to rucio/documentation.git denied to github-actions[bot].
> > fatal: unable to access '***github.com/rucio/documentation.git/': The requested URL returned error: 403
> > ```
> > 
> > 
> > So the changes are not pushed to GH Pages :/
> 
> Should work now.

Yeah I saw the changes have appeared on the website. Looks good! 👍

**Pull request merged**
